import type { D1Database, KVNamespace } from "@cloudflare/workers-types";
import type { WorkersAiBinding } from "./services/ai-classifier";

export type Env = {
  AI?: WorkersAiBinding;
  SCAN_JOB_KV?: KVNamespace;
  SCAN_JOB_DB?: D1Database;
  JWT_SECRET?: string;
  JWT_EXPIRES_SECONDS?: string;
  PROBE_API_KEY?: string;
  ALLOW_LOCAL_DEV_NO_AUTH?: string;
  GITHUB_TOKEN?: string;
  GITHUB_OWNER?: string;
  GITHUB_REPO?: string;
  GITHUB_LIVE_TLS_WORKFLOW?: string;
  GITHUB_LIGHTHOUSE_WORKFLOW?: string;
  GITHUB_BROWSER_RUNTIME_WORKFLOW?: string;
  GITHUB_REF?: string;
  AI_PROVIDER_API_KEY?: string;
  AI_PROVIDER_MODEL?: string;
  AI_PROVIDER_BASE_URL?: string;
  PAGESPEED_API_KEY?: string;
  PAGESPEED_API_URL?: string;
  WEBPAGETEST_API_KEY?: string;
  WEBPAGETEST_BASE_URL?: string;
  SCAN_JOB_HANDLE_SECRET?: string;
  SCAN_JOB_HANDLE_KID?: string;
  SCAN_JOB_HANDLE_TTL_SECONDS?: string;
  SCAN_JOB_HANDLE_MAX_PAYLOAD_BYTES?: string;
  SCAN_JOB_HANDLE_MAX_TOKEN_BYTES?: string;
  SCAN_JOB_TTL_SECONDS?: string;
  SCAN_JOB_MAX_OBJECT_BYTES?: string;
};
